### ISSUE TITLE
EmbedExtractorTest.testDivCaption has an expectation not conform with Element#innerText

### ISSUE THREAD

**Issue by yosinch** [chromium/dom-distiller#11]
In `EmbedExtractorTest.testDivCaption`, test expectation
```java
        String expected =
            "<figure>" +
                "<img src=\"http://wwww.example.com/image.jpeg\"" +
                    " width=\"100\" height=\"100\">" +
                "<figcaption>\nThis is a caption</figcaption>" +
            "</figure>";
        EmbedExtractor extractor = new ImageExtractor();
        WebElement result = extractor.extract(figure);
        assertEquals(expected, TestUtil.removeAllDirAttributes(
                result.generateOutput(false)));
```
does not conform with `Element#innerText` specification[1], where inner text of `<figcaption> ` should be: `This is a caption` without newline.

This is cause by current Blink's broken `Element#innerText` for
```html
<figure><img src="..." ...><div>This is a caption</div></figure>
```
assembled by `ImageExtractor.createFigcaptionElement()` which takes `<img>` as input parameter and uses `Element#innerText` for `<img>` and broken `Element#innerText` produces `\n` for `<div>`.

If leading newline is not significant, could you change `ImageExtractor.createFigcaptionElement()` to get rid of leading newline character?

[1] https://html.spec.whatwg.org/multipage/dom.html#the-innertext-idl-attribute

**Comment by wychen** [comment]
This fails in latest Firefox as well.
